# Generated by Django 3.2.12 on 2022-04-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grasps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
