# Generated by Django 3.2.12 on 2022-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grasps', '0002_auto_20220414_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(default='email@contact.com', max_length=200),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='password1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
