# Generated by Django 3.2.12 on 2022-04-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grasps', '0003_auto_20220414_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='check',
        ),
    ]
