# Generated by Django 3.2.12 on 2022-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grasps', '0004_remove_sign_up_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
